### ISSUE TITLE
Additional Currencies 

### ISSUE THREAD

**Issue by PeachfolioCryptoApe** [Peachfolio/V1-Beta#10]
To extend the selection of currencies available. 

Initial request has come in for Indonesian Rupiah and Japan Yen. Will monitor and add to this ticket when other currencies are requested or it will form part of the change item review. 

Abu Aquilla
Oh 1 more thing, can you add the option to choose currency from different country. Like Indonesian Rupiah, Japan Yen, Etc. 
Thank you.

**Comment by Dovysh9999** [comment]
Few things:

Add stacking option, it will give more purpose of buying token and accumulating in marketcap. 

Fix refresh function when you turn off Internet and turn on you have to close app, make that it would refresh when internet on without app close

Add farm function 

Make rewards function for holding

For now its enough thanks.
